project:
  type: book

book:
  title: "Curso auto-administrado para el diseño de tableros interactivos con Looker Studio"
  author: "Andrés Pereira / OPS"
  chapters:
    - index.qmd
    - modulo1.qmd
    - modulo2.qmd
    - modulo3.qmd
    - modulo4.qmd
    - modulo5.qmd

format:
  html:
    embed-resources: true # para que renderice con los elementos
    published-title: "Fecha:"  # Cambia "Published" por "Fecha"
    author-title: 
    toc: true                # Habilita la tabla de contenidos
    toc-title: "Índice de Contenidos"  # Título del índice
    toc-depth: 3             # Nivel de profundidad del índice (hasta h3)
    toc-location: right       # Ubicación del índice (derecha)
    code-tools: false
    number-sections: false
    css: styles.css 
